// Shapes of the JSON files generated by scripts/build-gamedata.ts.

export interface Ingredient {
  /** Market item ID, e.g. `T5_ORE_LEVEL1@1`. */
  id: string
  count: number
}

/** A refining recipe. Crafting has its own shape (CraftRecipe), with alternatives and returns per ingredient. */
export interface Recipe {
  /** Market item ID of the product, e.g. `T5_METALBAR_LEVEL1@1`. */
  id: string
  tier: number
  enchant: number
  /** Item value, used for the station usage fee. */
  itemValue: number
  /** Base focus cost per craft, before spec reductions. */
  focus: number
  /** Items produced per craft. */
  amount: number
  ingredients: Ingredient[]
}

export interface RefiningRecipe extends Recipe {
  /** The raw resource, e.g. 3× T5 ore. */
  raw: Ingredient
  /** The lower-tier refined item, e.g. 1× T4 bar. `null` for T2. */
  lower: Ingredient | null
}

export interface RefiningFamily {
  key: string
  name: string
  rawName: string
  /** Royal city with the refining specialization for this family. */
  bonusCity: string
  recipes: RefiningRecipe[]
}

export interface RefiningData {
  generatedAt: string
  /** Base production bonus in a royal city (0.18). */
  royalCityBonus: number
  /** Extra production bonus in the family's specialization city (0.40). */
  specializationBonus: number
  families: RefiningFamily[]
}

/** What an ingredient is. Where it's bought from is saved per kind. */
export type IngredientKind =
  | 'metalbar'
  | 'leather'
  | 'cloth'
  | 'planks'
  | 'artifact'
  | 'token'
  | 'sigil'
  | 'base'
  | 'cape'
  | 'crest'
  | 'heart'
  | 'energy'
  | 'tome'
  | 'part'

export interface CraftIngredient {
  /** Name without the tier word, e.g. "Remnants of the Old King", or the material ("Metal Bar"). */
  name: string
  kind: IngredientKind
  itemValue: number
}

/** One ingredient of a recipe. It can have alternatives, e.g. an artifact or a token. */
export interface CraftSlot {
  /** Market item IDs; the first is the default, the rest are alternatives. */
  options: string[]
  count: number
  /** Whether the return rate gives some back. Artifacts and other special ingredients: no. */
  returned: boolean
  /** The product keeps this ingredient's quality (the base item of royal items and faction capes). */
  preserveQuality?: true
}

export interface CraftRecipe {
  /** Market item ID of the product, e.g. `T4_2H_CLAYMORE_AVALON@1`. */
  id: string
  tier: number
  enchant: number
  /** Base focus cost per craft, before specs. */
  focus: number
  /** Sum of the ingredients' item values (default options), used for the usage fee. */
  itemValue: number
  /** Crafting fame of one craft, before Premium. This is what fills labourer journals. */
  fame: number
  slots: CraftSlot[]
}

export type JournalKind = 'WARRIOR' | 'HUNTER' | 'MAGE' | 'TOOLMAKER'

export interface CraftItem {
  /** Item ID without the tier, e.g. `2H_CLAYMORE_AVALON`. Used in page addresses. */
  key: string
  name: string
  /** Crafting category for the city bonus, e.g. `sword`. Upgrade recipes use their base item's. */
  category: string | null
  /** City with the extra crafting bonus for the category. */
  bonusCity: string | null
  /** Labourer journal the item fills, if crafting it gives fame. */
  journal: JournalKind | null
  recipes: CraftRecipe[]
}

export interface TreeNode {
  key: string
  name: string
  children?: TreeNode[]
  /** Item keys. */
  items?: string[]
}

export interface Journal {
  kind: JournalKind
  /** e.g. "Blacksmith's Journal" */
  name: string
  /** Fame a journal holds, per tier. */
  maxFame: Record<number, number>
}

export interface CraftingData {
  generatedAt: string
  /** Base production bonus in every royal city and Brecilien (0.18). */
  craftingBonus: number
  /** Extra bonus per crafting category, and the city that gives it. */
  categoryBonus: Record<string, { city: string; bonus: number }>
  tree: TreeNode[]
  items: CraftItem[]
  /** Every ingredient used by the recipes, by market item ID. */
  ingredients: Record<string, CraftIngredient>
  journals: Journal[]
}

/** The foundry's fragments, from the lowest power level to the highest. */
export type FragmentKey = 'rune' | 'soul' | 'relic' | 'shard'
/** The foundry's categories: red, blue, green and all three together. */
export type FoundryCategoryKey = 'warrior' | 'mage' | 'hunter' | 'all'

export interface FoundryFragment {
  key: FragmentKey
  /** e.g. "Rune", "Avalonian Shard" */
  name: string
  /** Market ID without the tier, e.g. `RUNE`, `SHARD_AVALONIAN`. */
  code: string
}

export interface FoundryCategory {
  key: FoundryCategoryKey
  /** e.g. "Warrior" */
  name: string
  /** Colour in the game data: red, blue, green or all. */
  aspect: string
}

/** A way to make a fragment at the foundry: 5 of the tier below, or the power level below + silver. */
export interface FragmentConversion {
  /** Market ID of the fragment used, e.g. `T5_RUNE`. */
  from: string
  count: number
  silver: number
}

/** A meld: fragments in, one random artifact from the pool out. */
export interface FoundryRecipe {
  tier: number
  fragment: FragmentKey
  category: FoundryCategoryKey
  /** Market ID of the fragment, e.g. `T6_RUNE`. */
  fragmentId: string
  /** Fragments per meld: 50, or 36 for All. */
  count: number
  /** Market IDs of the artifacts that can come out. Each has the same chance. */
  pool: string[]
}

export interface FoundryData {
  generatedAt: string
  fragments: FoundryFragment[]
  categories: FoundryCategory[]
  /** T4–T8 × fragment × category. */
  recipes: FoundryRecipe[]
  /** Ways to make each fragment from cheaper ones, by market ID. T4 runes can only be bought. */
  conversions: Record<string, FragmentConversion[]>
  /** Artifact names without the tier word, by market ID without the tier (`ARTEFACT_2H_HAMMER_UNDEAD`). */
  names: Record<string, string>
}
