// Shapes of the JSON files generated by scripts/build-gamedata.ts.

export interface Ingredient {
  /** Market item ID, e.g. `T5_ORE_LEVEL1@1`. */
  id: string
  count: number
}

/** A generic crafting recipe. Refining and (later) crafting both use this shape. */
export interface Recipe {
  /** Market item ID of the product, e.g. `T5_METALBAR_LEVEL1@1`. */
  id: string
  tier: number
  enchant: number
  /** Item value, used for the station usage fee. */
  itemValue: number
  /** Base focus cost per craft, before spec reductions. */
  focus: number
  /** Items produced per craft. */
  amount: number
  ingredients: Ingredient[]
}

export interface RefiningRecipe extends Recipe {
  /** The raw resource, e.g. 3× T5 ore. */
  raw: Ingredient
  /** The lower-tier refined item, e.g. 1× T4 bar. `null` for T2. */
  lower: Ingredient | null
}

export interface RefiningFamily {
  key: string
  name: string
  rawName: string
  /** Royal city with the refining specialization for this family. */
  bonusCity: string
  recipes: RefiningRecipe[]
}

export interface RefiningData {
  generatedAt: string
  /** Base production bonus in a royal city (0.18). */
  royalCityBonus: number
  /** Extra production bonus in the family's specialization city (0.40). */
  specializationBonus: number
  families: RefiningFamily[]
}
